import { ethers, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with account:", deployer.address);

  // 1. Deploy ZKTranscriptLib (external library used by HonkVerifier)
  const ZKTranscriptLib = await ethers.getContractFactory("ZKTranscriptLib");
  const zkTranscriptLib = await ZKTranscriptLib.deploy();
  await zkTranscriptLib.waitForDeployment();
  const zkTranscriptLibAddress = await zkTranscriptLib.getAddress();
  console.log("ZKTranscriptLib deployed to:", zkTranscriptLibAddress);

  // 2. Deploy HonkVerifier (generated by bb write_solidity_verifier), linked to ZKTranscriptLib
  const Verifier = await ethers.getContractFactory("HonkVerifier", {
    libraries: { ZKTranscriptLib: zkTranscriptLibAddress },
  });
  const verifier = await Verifier.deploy();
  await verifier.waitForDeployment();
  const verifierAddress = await verifier.getAddress();
  console.log("HonkVerifier deployed to:", verifierAddress);

  // 3. Deploy ElectionFactory
  const Factory = await ethers.getContractFactory("ElectionFactory");
  const factory = await Factory.deploy();
  await factory.waitForDeployment();
  const factoryAddress = await factory.getAddress();
  console.log("ElectionFactory deployed to:", factoryAddress);

  // 4. Persist addresses
  const deploymentsDir = path.join(__dirname, "../deployments");
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir, { recursive: true });
  }

  const deploymentData = {
    network: network.name,
    deployedAt: new Date().toISOString(),
    deployer: deployer.address,
    contracts: {
      ZKTranscriptLib: zkTranscriptLibAddress,
      HonkVerifier: verifierAddress,
      ElectionFactory: factoryAddress,
    },
  };

  const outputPath = path.join(deploymentsDir, `${network.name}.json`);
  fs.writeFileSync(outputPath, JSON.stringify(deploymentData, null, 2));
  console.log("Deployment info written to:", outputPath);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
