/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  BaseZKHonkVerifier,
  BaseZKHonkVerifierInterface,
} from "../../Verifier.sol/BaseZKHonkVerifier";

const _abi = [
  {
    inputs: [],
    name: "ConsistencyCheckFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "GeminiChallengeInSubgroup",
    type: "error",
  },
  {
    inputs: [],
    name: "InvertOfZero",
    type: "error",
  },
  {
    inputs: [],
    name: "NotPowerOfTwo",
    type: "error",
  },
  {
    inputs: [],
    name: "PointAtInfinity",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "logN",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "actualLength",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expectedLength",
        type: "uint256",
      },
    ],
    name: "ProofLengthWrongWithLogN",
    type: "error",
  },
  {
    inputs: [],
    name: "PublicInputsLengthWrong",
    type: "error",
  },
  {
    inputs: [],
    name: "ShpleminiFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "SumcheckFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "ValueGeFieldOrder",
    type: "error",
  },
  {
    inputs: [],
    name: "ValueGeGroupOrder",
    type: "error",
  },
  {
    inputs: [],
    name: "ValueGeLimbMax",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "publicInputs",
        type: "bytes32[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class BaseZKHonkVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): BaseZKHonkVerifierInterface {
    return new Interface(_abi) as BaseZKHonkVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BaseZKHonkVerifier {
    return new Contract(address, _abi, runner) as unknown as BaseZKHonkVerifier;
  }
}
