/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { Errors, ErrorsInterface } from "../../Verifier.sol/Errors";

const _abi = [
  {
    inputs: [],
    name: "ConsistencyCheckFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "GeminiChallengeInSubgroup",
    type: "error",
  },
  {
    inputs: [],
    name: "InvertOfZero",
    type: "error",
  },
  {
    inputs: [],
    name: "ModExpFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "NotPowerOfTwo",
    type: "error",
  },
  {
    inputs: [],
    name: "PointAtInfinity",
    type: "error",
  },
  {
    inputs: [],
    name: "ProofLengthWrong",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "logN",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "actualLength",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expectedLength",
        type: "uint256",
      },
    ],
    name: "ProofLengthWrongWithLogN",
    type: "error",
  },
  {
    inputs: [],
    name: "PublicInputsLengthWrong",
    type: "error",
  },
  {
    inputs: [],
    name: "ShpleminiFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "SumcheckFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "ValueGeFieldOrder",
    type: "error",
  },
  {
    inputs: [],
    name: "ValueGeGroupOrder",
    type: "error",
  },
  {
    inputs: [],
    name: "ValueGeLimbMax",
    type: "error",
  },
] as const;

const _bytecode =
  "0x602c6032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea164736f6c634300081c000a";

type ErrorsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ErrorsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Errors__factory extends ContractFactory {
  constructor(...args: ErrorsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Errors & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Errors__factory {
    return super.connect(runner) as Errors__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ErrorsInterface {
    return new Interface(_abi) as ErrorsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Errors {
    return new Contract(address, _abi, runner) as unknown as Errors;
  }
}
